language: php

php:
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install --dev --prefer-dist -o
  - echo $SENDGRID_API_TOKEN > .env

script:
  - ./vendor/bin/phpunit
